name: flutter_weather
description: "A weather application made with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.2.0
  dio: ^5.4.1
  blur: ^3.1.0
  flutter_screenutil: ^5.9.0
  eva_icons_flutter: ^3.1.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  weather_api:
    path: packages/weather_api
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800
